name: Python application

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4  # Atualizado para usar Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Atualizado para usar Node.js 20
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s test -p "*.py"

  build:

    runs-on: ubuntu-latest
    needs: test  # Esta linha garante que a build só será executada se os testes passarem

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4  # Atualizado para usar Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Atualizado para usar Node.js 20
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build application
      run: |
        
